#namespace: 36b5a6d6-37ac-4cfd-aa3a-4d308d954539
#group: cloud-demo
#
#spring:
#  application:
#    name: cloud-consumer
#  cloud:
#    nacos:
#      server-addr: 127.0.0.1:8848
#      password: nacos
#      username: nacos
#      discovery:
#        namespace: ${namespace}
#        group: ${group}
#      config:
#        namespace: ${namespace}
#        group: ${group}
#        file-extension: yaml
#  config:
#    import: optional:nacos:cloud-consumer-q.yaml
#
##server:
##  port: 8071