server:
  servlet:
    context-path:
  port: 8080

knife4j:
  enable: true

springdoc:
  swagger-ui:
    url: /doc/openapi.json

spring:
  profiles:
    active: @profile.active@
  config:
    import:
      - classpath:/config/${spring.profiles.active}/biz.yml