@startuml
'https://plantuml.com/sequence-diagram

autonumber

filterChain -> OAuth2TokenEndpointFilter: doFilterInternal
OAuth2TokenEndpointFilter -> DelegatingAuthenticationConverter: convert
DelegatingAuthenticationConverter -> OAuth2ClientCredentialsAuthenticationConverter: convert
OAuth2ClientCredentialsAuthenticationConverter --> DelegatingAuthenticationConverter: Authentication
DelegatingAuthenticationConverter --> OAuth2TokenEndpointFilter: Authentication
OAuth2TokenEndpointFilter -> ProviderManager: authenticate
ProviderManager -> OAuth2ClientCredentialsAuthenticationProvider: authenticate
OAuth2ClientCredentialsAuthenticationProvider -> DelegatingOAuth2TokenGenerator: generate
DelegatingOAuth2TokenGenerator --> OAuth2ClientCredentialsAuthenticationProvider: OAuth2Token
OAuth2ClientCredentialsAuthenticationProvider -> JdbcOAuth2AuthorizationService: save
JdbcOAuth2AuthorizationService --> OAuth2ClientCredentialsAuthenticationProvider: save
OAuth2ClientCredentialsAuthenticationProvider --> ProviderManager: Authentication + OAuth2Token
ProviderManager --> OAuth2TokenEndpointFilter: authenticate

@enduml