@startuml
'https://plantuml.com/sequence-diagram

autonumber

filterChain ->OAuth2ClientAuthenticationFilter: doFilterInternal
OAuth2ClientAuthenticationFilter -> DelegatingAuthenticationConverter: convert
DelegatingAuthenticationConverter -> ClientSecretPostAuthenticationConverter: convert
ClientSecretPostAuthenticationConverter --> DelegatingAuthenticationConverter: Authentication
DelegatingAuthenticationConverter --> OAuth2ClientAuthenticationFilter: Authentication
OAuth2ClientAuthenticationFilter -> ProviderManager: authenticate
ProviderManager -> ClientSecretAuthenticationProvider: authenticate
ClientSecretAuthenticationProvider -> JdbcRegisteredClientRepository: findByClientId
JdbcRegisteredClientRepository --> ClientSecretAuthenticationProvider: RegisteredClient
ClientSecretAuthenticationProvider -> DelegatingPasswordEncoder: matches
DelegatingPasswordEncoder --> ClientSecretAuthenticationProvider: boolean
ClientSecretAuthenticationProvider --> ProviderManager: authenticate

ProviderManager --> OAuth2ClientAuthenticationFilter: Authentication
OAuth2ClientAuthenticationFilter --> filterChain: Authentication









@enduml